### ISSUE TITLE
Bug: Handle ForbiddenException when failing to authenticate an inaccessible or non-existent account

### ISSUE THREAD

**Issue by tjninex** [spackle0/sso_gen#14]
An unhandled `ForbiddenException` is being thrown when attempting to authenticate an account that was removed.

```
Traceback (most recent call last):
  File "/home/t/projects/sso_gen/ssogen.py", line 7, in <module>
    main()
  File "/home/t/projects/sso_gen/sso_gen/__init__.py", line 20, in main
    configuation_files.process_credentials()
  File "/home/t/projects/sso_gen/sso_gen/aws_profile.py", line 102, in process_credentials
    creds = self.sso_client.get_role_creds(account_id, role_name)
  File "/home/t/projects/sso_gen/sso_gen/sso.py", line 117, in get_role_creds
    response = self.client.get_role_credentials(
  File "/home/t/.asdf/installs/python/3.10.2/lib/python3.10/site-packages/botocore/client.py", line 508, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/home/t/.asdf/installs/python/3.10.2/lib/python3.10/site-packages/botocore/client.py", line 915, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (ForbiddenException) when calling the GetRoleCredentials operation: No access
```

Added detail: The account in question was closed and is no longer accessible.

**Comment by spackle0** [comment]
If an account is closed, it isn't removed from your SSO login screen for 90 days unless you remove it from the org. I will account for this situation.
